### ISSUE TITLE
Trouble getting wifi working on ubuntu 22.04

### ISSUE THREAD

**Issue by nicolas-t** [lightrush/framework-laptop-formula#31]
Hello,

Thanks for your formula, it helped me a lot on ubuntu 21.

I recently made a clean install of ubuntu 22.04 (Linux 5.15), and Wifi stopped worked after a few days.
When I run
`sudo salt-call -l error --local --file-root="$(pwd)" state.apply framework-laptop.intel-ax210-workaround`

I get: 
```
local:
----------
          ID: intel_ax210_workaround_linux_generic_latest
    Function: pkg.latest
        Name: linux-generic-hwe-20.04
      Result: True
     Comment: Package linux-generic-hwe-20.04 is already up-to-date
     Started: 18:51:14.702797
    Duration: 1324.113 ms
     Changes:   
----------
          ID: intel_ax210_workaround_service_dead
    Function: service.dead
        Name: intel-ax210-workaround
      Result: True
     Comment: The named service intel-ax210-workaround is not available
     Started: 18:51:16.035617
    Duration: 4.695 ms
     Changes:   
----------
          ID: intel_ax210_workaround_service_removed
    Function: file.absent
        Name: /etc/systemd/system/intel-ax210-workaround.service
      Result: True
     Comment: File /etc/systemd/system/intel-ax210-workaround.service is not present
     Started: 18:51:16.041953
    Duration: 0.354 ms
     Changes:   
----------
          ID: intel_ax210_workaround_service_removed
    Function: module.run
        Name: service.systemctl_reload
      Result: True
     Comment: State was not run because none of the onchanges reqs changed
     Started: 18:51:16.042977
    Duration: 0.002 ms
     Changes:   
----------
          ID: intel_ax210_workaround_firmware_restored
    Function: cmd.run
        Name: /bin/sh -c "mv -f /lib/firmware/iwlwifi-ty-a0-gf-a0.pnvm.renamed-by-salt /lib/firmware/iwlwifi-ty-a0-gf-a0.pnvm ; rmmod iwlmvm ; rmmod iwlwifi ; modprobe iwlwifi"
      Result: True
     Comment: unless condition is true
     Started: 18:51:16.043511
    Duration: 308.665 ms
     Changes:   
----------
          ID: intel_ax210_workaround_firmware_reinstalled
    Function: pkg.installed
        Name: linux-firmware
      Result: True
     Comment: unless condition is true
     Started: 18:51:16.352294
    Duration: 4.037 ms
     Changes:   
----------
          ID: intel_ax210_workaround_modprobe_conf_removed
    Function: file.absent
        Name: /etc/modprobe.d/intel-ax210-workaround.conf
      Result: True
     Comment: File /etc/modprobe.d/intel-ax210-workaround.conf is not present
     Started: 18:51:16.356399
    Duration: 0.282 ms
     Changes:   
----------
          ID: intel_ax210_workaround_initramfs_updated
    Function: cmd.run
        Name: update-initramfs -u
      Result: True
     Comment: State was not run because none of the onchanges reqs changed
     Started: 18:51:16.356879
    Duration: 0.001 ms
     Changes:   

Summary for local
------------
Succeeded: 8
Failed:    0
------------
Total states run:     8
Total run time:   1.642 s

```

And if I try the workaround described [here ](https://github.com/lightrush/framework-laptop-formula#attention-in-case-of-broken-wifi-on-intel-ax210) immediatly after 
I get : 
```
$ sudo systemctl disable intel-ax210-workaround.service
  > Failed to disable unit: Unit file intel-ax210-workaround.service does not exist.
$ sudo mv /lib/firmware/iwlwifi-ty-a0-gf-a0.pnvm.renamed-by-salt /lib/firmware/iwlwifi-ty-a0-gf-a0.pnvm
  > mv: cannot stat '/lib/firmware/iwlwifi-ty-a0-gf-a0.pnvm.renamed-by-salt': No such file or directory
$ sudo rmmod iwlmvm
$ sudo rmmod iwlwifi
$ sudo modprobe iwlwifi
$ 
```

I tried booting ubuntu 22 from a usb key and wifi didn't work there either.

I'm a bit lost as how to fix this issue do you have any idea of what's going on ? 

Thanks

**Comment by lightrush** [comment]
[The workaround](https://github.com/lightrush/framework-laptop-formula#attention-in-case-of-broken-wifi-on-intel-ax210) you tried is only relevant if you were running 20.04.3 or earlier with kernel 5.11. WiFi was broken on 5.11 which required the ax210 workaround the formula applies. Sometime between 20.04.3 and 20.04.4 the kernel got upgraded to 5.13 at which point WiFi broke for people who had used the formula because the *workaround broke* WiFi with 5.13. [So this](https://github.com/lightrush/framework-laptop-formula#attention-in-case-of-broken-wifi-on-intel-ax210) is to undo that so people get their WiFi back. The formula looks at the current kernel. If it sees it's not 5.11, it checks to find if it previously applied the ax210 workaround and if so, it removes it. It doesn't apply anything else on 20.04.4 or 22.04 as WiFi *should work* out of the box. So I'm afraid it won't solve your problem as it isn't relevant to it. You should probably post in the community forum with more details on the WiFi problem so more eyes can look at it.

**Comment by nicolas-t** [comment]
Thanks for your help! 
As explained on the forum [here](https://community.frame.work/t/wifi-stopped-working-on-ubuntu-22-04/17964) I chose to install install ubuntu 21 becuase I don't have the time to deal with this issues.
